# Generated by Django 6.0.1 on 2026-02-23 09:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAgent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('system_prompt', models.TextField(help_text='Instruções de comportamento enviadas como system message.')),
                ('model_name', models.CharField(default='gpt-4o', max_length=100)),
                ('temperature', models.FloatField(default=0.7)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'AI Agent',
                'verbose_name_plural': 'AI Agents',
                'ordering': ['name'],
            },
        ),
    ]
