# Generated by Django 5.2.11 on 2026-02-24 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='api_key_openai',
            new_name='llm_api_key',
        ),
    ]
