# Generated by Django 6.0.1 on 2026-03-11 23:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('organizations', '0002_rename_api_key_openai_organization_llm_api_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('twilio_phone_number', models.CharField(help_text='Número Twilio WhatsApp (ex: whatsapp:+5551999990000)', max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_configs', to='agents.aiagent')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_config', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'WhatsApp Config',
                'verbose_name_plural': 'WhatsApp Configs',
            },
        ),
    ]
