# Generated by Django 5.2.12 on 2026-03-11 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappconfig',
            name='twilio_phone_number',
            field=models.CharField(help_text='Número Twilio WhatsApp (ex: whatsapp:+5551999990000)', max_length=30, unique=True),
        ),
    ]
