# Generated by Django 6.0.1 on 2026-03-24 00:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_rename_api_key_openai_organization_llm_api_key'),
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='external_event_id',
            field=models.CharField(blank=True, default='', help_text='ID do evento no calendário externo (Google, Cal.com, Calendly)', max_length=255),
        ),
        migrations.CreateModel(
            name='CalendarConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('google', 'Google Calendar'), ('calcom', 'Cal.com'), ('calendly', 'Calendly')], max_length=20)),
                ('calendar_id', models.CharField(help_text='ID do calendário (Google), event type ID (Cal.com/Calendly)', max_length=255)),
                ('credentials', models.JSONField(default=dict, help_text='API key, tokens ou service account JSON conforme o provider')),
                ('business_hours', models.JSONField(blank=True, default=dict, help_text='Override de horários. Ex: {"mon": ["09:00", "18:00"], "sat": ["09:00", "16:00"], "sun": null}')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_config', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Configuração de Calendário',
                'verbose_name_plural': 'Configurações de Calendário',
            },
        ),
    ]
